// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SeniorProjectWebApplication.Data;
using System;

namespace SeniorProjectWebApplication.Migrations
{
    [DbContext(typeof(SeniorProjectWebApplicationContext))]
    [Migration("20180725023619_SecondUpdate")]
    partial class SecondUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeniorProjectWebApplication.Data.Measurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<float>("Pressure");

                    b.Property<int>("SessionNumber");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Measurement");
                });
#pragma warning restore 612, 618
        }
    }
}
